BROKER_HOSTNAME = "broker.mqttdashboard.com"
BROKER_PORT = 1883
MQTT_TOPIC = "ii22/telemetry/#"

DATABASE = "data/database.db"
EVENT = "Event"
ROBOT = "Robot"

# Possible States
STARVED = "READY-IDLE-STARVED"
BLOCKED = "READY-IDLE-BLOCKED"
IDLE = "idle"
EXECUTING = "READY-PROCESSING-EXECUTING"
PROCESSING = "processing"
ACTIVE = "READY-PROCESSING-ACTIVE"
ERROR = "error"
SETUP = "SETUP"
DOWN = "DOWN"
OFF = "OFF"